Repository FRONT-END-BOOTCAMP-PLUS-5/Fiterview, pull requests merged in 2025-08, with the labels that each got.

#6 fix: eslint fix
  .eslintrc.js
  .yarn/releases/yarn-4.9.2.cjs
  .yarnrc.yml
  eslint.config.mjs
  package.json
  yarn.lock
Labels: 🐞BUG

#3 chore: 폴더 구조 정립
  app/(anon)/home/components/ex.tsx
  app/(anon)/interview/components/ex.tsx
  app/(anon)/interview/page.tsx
  app/(anon)/login/components/ex.tsx
  app/(anon)/login/page.tsx
  app/(anon)/my/components/ex.tsx
  app/(anon)/my/page.tsx
  app/(anon)/page.tsx
  app/(anon)/reports/[id]/components/ex.tsx
  app/(anon)/reports/[id]/page.tsx
  app/(anon)/reports/components/ex.tsx
  app/(anon)/reports/page.tsx
  app/(anon)/signup/components/ex.tsx
  app/(anon)/signup/page.tsx
  app/api/reports/[id]/route.ts
  app/api/reports/route.ts
  app/api/users/login/route.ts
  app/api/users/logout/route.ts
  app/api/users/siginup/route.ts
  app/components/ex.tsx
  app/page.tsx
  backend/ai/llm/domain/.gitkeep
  backend/ai/llm/infrastructure/.gitkeep
  backend/ai/stt/domain/.gitkeep
  backend/ai/stt/infrastructure/.gitkeep
  backend/ai/tts/domain/.gitkeep
  backend/ai/tts/infrastructure/.gitkeep
  backend/auths/login/application/dtos/.gitkeep
  backend/auths/login/application/usecasees/.gitkeep
  backend/auths/login/domain/entities/.gitkeep
  backend/auths/login/domain/repositories/.gitkeep
  backend/auths/login/infrastructure/repositories/.gitkeep
  backend/feedbacks/application/dtos/.gitkeep
  backend/feedbacks/application/usecasees/.gitkeep
  backend/feedbacks/domain/entities/.gitkeep
  backend/feedbacks/domain/repositories/.gitkeep
  backend/feedbacks/infrastructure/repositories/.gitkeep
  backend/questions/application/dtos/.gitkeep
  backend/questions/application/usecasees/.gitkeep
  backend/questions/domain/entities/.gitkeep
  backend/questions/domain/repositories/.gitkeep
  backend/questions/infrastructure/repositories/.gitkeep
  backend/reports/application/dtos/.gitkeep
  backend/reports/application/usecasees/.gitkeep
  backend/reports/domain/entities/.gitkeep
  backend/reports/domain/repositories/.gitkeep
  backend/reports/infrastructure/repositories/.gitkeep
  backend/users/application/dtos/.gitkeep
  backend/users/application/usecasees/.gitkeep
  backend/users/domain/entities/.gitkeep
  backend/users/domain/repositories/.gitkeep
  backend/users/infrastructure/repositories/.gitkeep
  constants/.gitkeep
  eslint.config.mjs
  hooks/.gitkeep
  lib/.gitkeep
  stores/.gitkeep
  utils/.gitkeep
  yarn.lock
Labels: 🍀 FE, 🔥 BE, 💫 FEAT

#16 refactor: 클린 아키텍처 패턴에 맞게 backend 폴더 구조 정리
  backend/application/ai/llm/.gitkeep
  backend/application/ai/stt/.gitkeep
  backend/application/ai/tts/.gitkeep
  backend/application/auth/login/dtos/.gitkeep
  backend/application/auth/login/usecases/.gitkeep
  backend/application/feedbacks/dtos/.gitkeep
  backend/application/feedbacks/usecases/.gitkeep
  backend/application/questions/dtos/.gitkeep
  backend/application/questions/usecases/.gitkeep
  backend/application/reports/dtos/.gitkeep
  backend/application/reports/usecases/.gitkeep
  backend/application/users/dtos/.gitkeep
  backend/application/users/usecases/.gitkeep
  backend/auths/login/application/dtos/.gitkeep
  backend/auths/login/application/usecasees/.gitkeep
  backend/auths/login/domain/entities/.gitkeep
  backend/auths/login/domain/repositories/.gitkeep
  backend/auths/login/infrastructure/repositories/.gitkeep
  backend/domain/entities/.gitkeep
  backend/domain/repositories/.gitkeep
  backend/infrastructure/mappers/.gitkeep
  backend/infrastructure/repositories/.gitkeep
  backend/infrastructure/types/.gitkeep
  backend/reports/domain/entities/.gitkeep
  backend/reports/domain/repositories/.gitkeep
  backend/reports/infrastructure/repositories/.gitkeep
  backend/users/application/dtos/.gitkeep
  backend/users/application/usecasees/.gitkeep
  backend/users/domain/entities/.gitkeep
  backend/users/domain/repositories/.gitkeep
  backend/users/infrastructure/repositories/.gitkeep
Labels: 🛠️ REFACTOR

#18 feat: tts 모델 연결
  .gitignore
  backend/application/questions/dtos/.gitkeep
  backend/application/questions/usecases/.gitkeep
  backend/application/questions/usecases/GenerateSpeechUsecase.ts
  backend/domain/dtos/TTSRequest.ts
  backend/domain/dtos/TTSResponse.ts
  backend/domain/entities/.gitkeep
  backend/domain/entities/Question.ts
  backend/domain/repositories/QuestionRepository.ts
  backend/domain/repositories/TTSRepository.ts
  backend/infrastructure/providers/TTSProvider.ts
  backend/infrastructure/repositories/TTSRepositoryImpl.ts
  package.json
  prisma/schema.prisma
  yarn.lock
Labels: 🔥 BE, 💫 FEAT

#20 refactor: stt 모델 연결 로직 수정
  app/api/stt-test/route.ts
  backend/domain/repositories/STTRepository.ts
  backend/infrastructure/providers/OpenAIProvider.ts
  backend/infrastructure/repositories/STTRepositoryImpl.ts
  public/assets/audios/test.m4a
  tsconfig.json
  yarn.lock
Labels: 🔥 BE, ⚙️ CHORE, 🛠️ REFACTOR

#19 feat: 파일 업로드로 리포트 생성 및 질문 생성/저장 흐름 구현
  app/api/reports/route.ts
  backend/application/questions/dtos/SavedQuestionsDto.ts
  backend/application/questions/usecases/GenerateQuestionsUseCase.ts
  backend/application/reports/usecases/.gitkeep
  backend/application/reports/usecases/CreateReportUsecase.ts
  backend/domain/dtos/QuestionsRequest.ts
  backend/domain/dtos/QuestionsResponse.ts
  backend/domain/entities/Question.ts
  backend/domain/entities/Report.ts
  backend/domain/repositories/QuestionRepository.ts
  backend/domain/repositories/ReportRepository.ts
  backend/infrastructure/mappers/.gitkeep
  backend/infrastructure/mappers/ReportStatusMapper.ts
  backend/infrastructure/providers/GoogleAIProvider.ts
  backend/infrastructure/repositories/GenerateQuestionRepositoryImpl.ts
  backend/infrastructure/repositories/PrQuestionRepository.ts
  backend/infrastructure/repositories/PrReportRepository.ts
  constants/.gitkeep
  constants/questions.ts
  package.json
  prisma/schema.prisma
  yarn.lock
Labels: 🔥 BE, 💫 FEAT

#22 feat: 질문 조회 응답값 수정
  backend/infrastructure/repositories/PrQuestionRepository.ts
Labels: 🔥 BE, 💫 FEAT

#38 feat: STT 연결 완료
  app/(anon)/interview/questions/page.tsx
  app/api/reports/[id]/questions/[order]/transcribe/route.ts
  backend/application/questions/usecases/GetAudioByQuestionUseCase.ts
  backend/application/questions/usecases/TranscribeAudioUseCase.ts
  backend/domain/entities/Question.ts
  backend/domain/repositories/QuestionRepository.ts
  backend/infrastructure/AI/TranscribeSttAI.ts
  backend/infrastructure/repositories/QuestionRepositoryImpl.ts
  backend/infrastructure/services/FileProcessingService.ts
  public/assets/audios/test.m4a
  utils/.gitkeep
Labels: 🔥 BE, 💫 FEAT, 🛠️ REFACTOR

#44 fix: SVG props 동적 오버라이드 지원
  .svgrrc.js
  app/(anon)/interview/page.tsx
  next.config.ts
  public/assets/icons/arrow.svg
  public/assets/icons/audio-bars.svg
  public/assets/icons/bar-chart.svg
  public/assets/icons/brain.svg
  public/assets/icons/check-circle.svg
  public/assets/icons/check.svg
  public/assets/icons/clock.svg
  public/assets/icons/delete.svg
  public/assets/icons/edit.svg
  public/assets/icons/frame.svg
  public/assets/icons/headphone.svg
  public/assets/icons/history.svg
  public/assets/icons/home.svg
  public/assets/icons/image.svg
  public/assets/icons/logout.svg
  public/assets/icons/message-circle.svg
  public/assets/icons/message-square.svg
  public/assets/icons/pause.svg
  public/assets/icons/play.svg
  public/assets/icons/refresh.svg
  public/assets/icons/rocket.svg
  public/assets/icons/skip-forward.svg
  public/assets/icons/square.svg
  public/assets/icons/star.svg
  public/assets/icons/upload.svg
  public/assets/icons/user.svg
  public/assets/icons/x.svg
  svgr.d.ts
Labels: ⚙️ CHORE

#54 feat: 면접 페이지 구현(tts 재생~녹음 저장 및 다음 질문 이동 플로우 생성)
  app/(anon)/interview/[id]/components/AiAvatar.tsx
  app/(anon)/interview/[id]/components/BottomSection.tsx
  app/(anon)/interview/[id]/components/InterviewClient.tsx
  app/(anon)/interview/[id]/components/Question.tsx
  app/(anon)/interview/[id]/components/Timer.tsx
  app/(anon)/interview/[id]/components/TopSection.tsx
  app/(anon)/interview/[id]/components/UserAudio.tsx
  app/(anon)/interview/[id]/components/UserCamera.tsx
  app/(anon)/interview/[id]/page.tsx
  app/components/QueryProvider.tsx
  app/layout.tsx
  hooks/useGetTtsQuestions.tsx
  hooks/useTtsAutoPlay.ts
  public/assets/icons/character.svg
  types/interview.ts
Labels: 🍀 FE, 💫 FEAT, 🎡Publish

#55 feat: 공통 모달 및 interview페이지 모달 연결
  app/(anon)/components/LoadingSpinner.tsx
  app/(anon)/components/QueryProvider.tsx
  app/(anon)/components/modal/LoginModal.tsx
  app/(anon)/components/modal/LogoutModal.tsx
  app/(anon)/components/modal/Modal.tsx
  app/(anon)/components/modal/ModalOverlay.tsx
  app/(anon)/interview/components/FileItem.tsx
  app/(anon)/interview/components/NoneUploadFiles.tsx
  app/(anon)/interview/components/PendingInterviewsList.tsx
  app/(anon)/interview/components/QuickInterviewForm.tsx
  app/(anon)/interview/components/UploadOptions.tsx
  app/(anon)/interview/components/UploadedFiles.tsx
  app/(anon)/interview/components/modal/ErrorModal.tsx
  app/(anon)/interview/components/modal/GenerateQuestionModal.tsx
  app/(anon)/interview/page.tsx
  app/layout.tsx
  public/assets/icons/check-circle.svg
  stores/.gitkeep
  stores/useModalStore.ts
  stores/useReportStore.ts
  types/file.ts
Labels: 🍀 FE, 💫 FEAT

#58 feat: tts api에 사용자 인증 로직 추가 및 리액트 쿼리 에러 자동 재요청 안되게끔 수정
  app/(anon)/interview/[id]/components/InterviewClient.tsx
  app/api/reports/[id]/questions/tts/route.ts
  hooks/useGetTtsQuestions.tsx
Labels: 🔥 BE, 📞 API

#51 feat: 피드백 UI 생성
  app/(anon)/reports/[id]/components/AIFeedback.tsx
  app/(anon)/reports/[id]/page.tsx
  app/api/reports/[id]/feedback/route.ts
  app/api/reports/feedback/route.ts
  backend/infrastructure/repositories/FeedbackRepositoryImpl.ts
  constants/feedback.ts
  lib/auth/api-auth.ts
Labels: 🍀 FE, 💫 FEAT, 📞 API

#64 fix: Google OAuth 로그인 에러 해결
  app/(anon)/components/modal/LogoutModal.tsx
  app/(anon)/login/page.tsx
  app/api/auth/[...nextauth]/authOptions.ts
  hooks/useLogout.ts
  lib/auth/api-auth.ts
  next-auth.d.ts
Labels: 🐞BUG, 🔥 BE, 📞 API

#68 feat: 질문 생성 완료 모달 추가 및 대기 면접 리스트 패치
  app/(anon)/interview/components/InterviewDashboard.tsx
  app/(anon)/interview/components/NoneReports.tsx
  app/(anon)/interview/components/NoneUploadFiles.tsx
  app/(anon)/interview/components/PendingInterviewsList.tsx
  app/(anon)/interview/components/QuickInterviewForm.tsx
  app/(anon)/interview/components/UploadOptions.tsx
  app/(anon)/interview/components/UploadedFiles.tsx
  app/(anon)/interview/components/modal/FileAnalysisErrorModal.tsx
  app/(anon)/interview/components/modal/GenerateQuestionErrorModal.tsx
  app/(anon)/interview/components/modal/GenerateQuestionModal.tsx
  app/(anon)/interview/page.tsx
Labels: 🍀 FE, 💫 FEAT, 🛠️ REFACTOR

#73 인터뷰 마무리 후 피드백 생성 및 DB 저장
  app/(anon)/interview/[id]/components/InterviewClient.tsx
Labels: 🍀 FE, 📞 API

#75 feat: 리포트 상태 관리 시스템 구현
  app/(anon)/interview/[id]/components/InterviewClient.tsx
  app/(anon)/reports/[id]/components/AIFeedback.tsx
  app/(anon)/reports/[id]/components/AudioFileSection.tsx
  app/(anon)/reports/[id]/components/AudioReportViewer.tsx
  app/(anon)/reports/[id]/components/StatusBadge.tsx
  stores/useReportStatusStore.ts
  types/report.ts
Labels: 🍀 FE, 🔥 BE, 💫 FEAT

#80 회고 모달 UI 및 구조
  app/(anon)/interview/[id]/components/InterviewClient.tsx
  app/(anon)/interview/[id]/page.tsx
  app/(anon)/interview/components/modal/ReflectionModal.tsx
Labels: 🍀 FE, 💫 FEAT, 📞 API

#84 feat: report 페이지 통합
  app/(anon)/interview/[id]/components/precheck/CheckList.tsx
  app/(anon)/reports/[id]/components/AIFeedback.tsx
  app/(anon)/reports/[id]/components/AudioFileSection.tsx
  app/(anon)/reports/[id]/components/AudioReportViewer.tsx
  app/(anon)/reports/[id]/components/DeleteModal.tsx
  app/(anon)/reports/[id]/components/DeleteSection.tsx
  app/(anon)/reports/[id]/components/HeaderSection.tsx
  app/(anon)/reports/[id]/components/QuestionItem.tsx
  app/(anon)/reports/[id]/page.tsx
  app/api/reports/route.ts
  public/assets/icons/check.svg
  public/assets/icons/edit.svg
Labels: 🍀 FE, 🔥 BE, 💫 FEAT, 🛠️ REFACTOR

#102 feat: 면접 진행 시 STT/피드백 처리를 백그라운드로 이동하여 사용자 경험 개선
  app/(anon)/interview/[id]/components/InterviewClient.tsx
Labels: 🔥 BE, 🛠️ REFACTOR

#96 feat: 리포트 목록 페이지 구현 완료
  app/(anon)/interview/components/PendingInterviewsList.tsx
  app/(anon)/interview/components/ReportCard.tsx
  app/(anon)/reports/components/ReportDetailCard.tsx
  app/(anon)/reports/components/ReportsContent.tsx
  app/(anon)/reports/components/ReportsHeader.tsx
  app/(anon)/reports/components/ReportsList.tsx
  app/(anon)/reports/components/UserDashboard.tsx
  app/(anon)/reports/components/ex.tsx
  app/(anon)/reports/page.tsx
  app/api/reports/route.ts
  backend/application/reports/dtos/ReportDto.ts
  backend/domain/entities/Report.ts
  backend/infrastructure/repositories/ReportRepositoryImpl.ts
  hooks/usePagination.ts
  public/assets/icons/analyzing.svg
  public/assets/icons/complicated.svg
  public/assets/icons/divider.svg
  public/assets/icons/empty.svg
  public/assets/icons/file.svg
  public/assets/icons/play-circle.svg
Labels: 🍀 FE, 🔥 BE, 💫 FEAT, 📞 API

#98 feat: 리포트+질문 생성 진행률 표시 & 폴링 전환
  app/(anon)/components/layout/HeaderVisibility.tsx
  app/(anon)/components/loading/ProgressBar.tsx
  app/(anon)/components/modal/ErrorModal.tsx
  app/(anon)/components/modal/Modal.tsx
  app/(anon)/components/modal/ReportProgressModal.tsx
  app/(anon)/home/components/quick/InterviewFrom.tsx
  app/(anon)/interview/components/InterviewDashboard.tsx
  app/(anon)/interview/components/PendingInterviewsList.tsx
  app/(anon)/interview/components/QuickInterviewForm.tsx
  app/api/reports/progress/route.ts
  app/api/reports/route.ts
  app/globals.css
  backend/application/reports/usecases/CreateReportUsecase.ts
  constants/progress.ts
  hooks/useReportProgress.ts
  hooks/useUploadFiles.ts
  lib/server/progressStore.ts
  public/assets/icons/chat-round.svg
  public/assets/icons/mic-logo.svg
  public/assets/icons/target.svg
  stores/useReportStore.ts
  types/progress.ts
Labels: 🍀 FE, 🔥 BE, 💫 FEAT, 📞 API

#106 feat: css 수정
  app/(anon)/interview/[id]/components/avatar/Question.tsx
Labels: 🍀 FE, 🎡Publish

#103 feat: 홈 애니메이션 추가
  app/(anon)/home/components/FastFiterviewStart.tsx
  app/(anon)/home/components/FiterviewPrepare.tsx
  app/(anon)/home/components/FiterviewStart.tsx
  app/(anon)/home/components/FiterviewStrength.tsx
  app/(anon)/home/components/quick/InterviewFrom.tsx
  app/(anon)/interview/components/FileItem.tsx
  app/(anon)/interview/components/InterviewDashboard.tsx
  app/(anon)/interview/components/PendingInterviewsList.tsx
  app/(anon)/interview/components/QuickInterviewForm.tsx
Labels: 🍀 FE, 🎡Publish, 🛠️ REFACTOR

#95 Feat/login signup
  app/(anon)/login/page.tsx
  app/(anon)/reports/[id]/components/AIFeedback.tsx
  app/(anon)/reports/[id]/components/Reflection.tsx
  app/(anon)/signup/page.tsx
  app/globals.css
  app/layout.tsx
  public/assets/icons/logo-subtitle.svg
  public/assets/icons/logo2.svg
  public/fonts/GmarketSansTTFLight.ttf
  public/fonts/GmarketSansTTFMedium.ttf
Labels: 🍀 FE, 💫 FEAT, 📞 API

#110 refactor: 중복 헤더 코드 제거 및 Empty 상태 렌더링 개선
  app/(anon)/reports/components/ReportsList.tsx
  public/assets/icons/empty-circle.svg
  public/assets/icons/x-circle.svg
Labels: 🍀 FE, 🛠️ REFACTOR

#116 마이페이지 백엔드 및 프론트 기능 구현
  app/(anon)/components/Input.tsx
  app/(anon)/user/components/LabeledInput.tsx
  app/(anon)/user/components/StaticField.tsx
  app/(anon)/user/components/SubmitButton.tsx
  app/(anon)/user/page.tsx
  app/api/auth/[...nextauth]/authOptions.ts
  app/api/auth/user/route.ts
  backend/application/users/dtos/UpdateUserRequestDto.ts
  backend/application/users/usecases/.gitkeep
  backend/application/users/usecases/UpdateUserUseCase.ts
Labels: 🍀 FE, 🔥 BE, 📞 API

#127 feat: 워크 플로우 파일 (deploy-on-ubuntu-server.yml) 생성
  .github/workflows/deploy-on-ubuntu-server.yml
Labels: ⚙️ CHORE

#126 refactor: 미응시 면접 재생 비활성화
  app/(anon)/reports/[id]/components/AIFeedback.tsx
  app/(anon)/reports/[id]/components/AudioFileSection.tsx
  app/(anon)/reports/[id]/components/AudioPlayer.tsx
  app/(anon)/reports/[id]/components/AudioReportViewer.tsx
  app/(anon)/reports/[id]/components/DeleteSection.tsx
Labels: 🍀 FE, 🛠️ REFACTOR

#129 fix: 로그아웃 <->면접 삭제 모달 에러 해결
  app/(anon)/reports/[id]/components/DeleteSection.tsx
  app/components/layout/DropDown.tsx
  app/components/layout/Header.tsx
Labels: 🐞BUG, 🍀 FE

#140 refactor: 질문 생성 진행 모달 UI 개선 및 401 에러 해결
  app/(anon)/components/quick/InterviewFrom.tsx
  app/(anon)/interview/components/InterviewDashboard.tsx
  app/(anon)/interview/components/QuickInterviewForm.tsx
  app/(anon)/reports/components/ReportsContent.tsx
  app/components/loading/ProgressBar.tsx
  app/components/modal/ErrorModal.tsx
  app/components/modal/GenerateQuestionModal.tsx
  app/globals.css
Labels: 🍀 FE, 🛠️ REFACTOR
